[package]
name = "mandelbug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.170"
num = "0.4.3"
num-traits = "0.2"
rug = "1.27.0"
